---
title: "p8105_hw1_wz2590"
output: github_document
---



# Problem 1


```{r  problem 1-1, message = FALSE}
library(tidyverse)

set.seed(124)

## data frames
example_df = 
  tibble(
    n_distribution = rnorm(10),
    logical_vec = n_distribution > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("male", "male", "male", "female", "female", "female", 
                          "bisex", "bisex", "bisex", "bisex"))
  )
example_df
mean(example_df$n_distribution)
mean(example_df$logical_vec)
mean(example_df$char_vec)
mean(example_df$factor_vec)
```

```{r  problem 1-2, message = FALSE}
as.numeric(example_df$n_distribution)
as.numeric(example_df$logical_vec)
as.numeric(example_df$char_vec)
as.numeric(example_df$factor_vec)
```


# Problem 2
```{r  problem 2-1, message = FALSE}
data("penguins", package = "palmerpenguins")
penguins
```

This is a tibble dataset about penguins. The column headers are: 

The dimensions of this tibble: `r nrow(penguins)` * `r ncol(penguins)`

The mean flipper length in mm is: `r mean(penguins$flipper_length_mm, na.rm=TRUE)` mm


```{r  problem 2-2, message = FALSE}
ggplot(penguins, aes(x = flipper_length_mm, y = bill_length_mm, color = species)) + geom_point()
ggsave("P2_scatterplot.pdf", height = 4, width = 6)
```


